# Generated by Django 3.0.5 on 2020-05-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=64)),
                ('imageUrl', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=512)),
                ('category', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('imageUrl', models.URLField()),
                ('notes', models.CharField(blank=True, max_length=512)),
                ('isAvailable', models.BooleanField(default=True)),
                ('allergens', models.ManyToManyField(blank=True, related_name='drinkallergens_ingredients', to='dishes.Ingredient')),
                ('ingredients', models.ManyToManyField(blank=True, related_name='drinkingredients_ingredient', to='dishes.Ingredient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=512)),
                ('category', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('imageUrl', models.URLField()),
                ('notes', models.CharField(blank=True, max_length=512)),
                ('isAvailable', models.BooleanField(default=True)),
                ('allergens', models.ManyToManyField(blank=True, related_name='dishallergens_ingredients', to='dishes.Ingredient')),
                ('ingredients', models.ManyToManyField(blank=True, related_name='dishingredients_ingredient', to='dishes.Ingredient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Desert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=512)),
                ('category', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('imageUrl', models.URLField()),
                ('notes', models.CharField(blank=True, max_length=512)),
                ('isAvailable', models.BooleanField(default=True)),
                ('allergens', models.ManyToManyField(blank=True, related_name='desertallergens_ingredients', to='dishes.Ingredient')),
                ('ingredients', models.ManyToManyField(blank=True, related_name='desertingredients_ingredient', to='dishes.Ingredient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Appetizer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=512)),
                ('category', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('imageUrl', models.URLField()),
                ('notes', models.CharField(blank=True, max_length=512)),
                ('isAvailable', models.BooleanField(default=True)),
                ('allergens', models.ManyToManyField(blank=True, related_name='appetizerallergens_ingredients', to='dishes.Ingredient')),
                ('ingredients', models.ManyToManyField(blank=True, related_name='appetizeringredients_ingredient', to='dishes.Ingredient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
