# Generated by Django 3.0.5 on 2020-05-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appetizer',
            name='isAvailable',
            field=models.BooleanField(default=True, verbose_name='Is Available?'),
        ),
        migrations.AlterField(
            model_name='desert',
            name='isAvailable',
            field=models.BooleanField(default=True, verbose_name='Is Available?'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='isAvailable',
            field=models.BooleanField(default=True, verbose_name='Is Available?'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='isAvailable',
            field=models.BooleanField(default=True, verbose_name='Is Available?'),
        ),
    ]
