# Generated by Django 3.0.5 on 2020-05-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_auto_20200508_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appetizer',
            name='imageUrl',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='dessert',
            name='imageUrl',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='imageUrl',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='drink',
            name='imageUrl',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='imageUrl',
            field=models.URLField(blank=True),
        ),
    ]
